//
//  ReportPDFGenerator.swift
//  CureMeGPT
//
//  Created by Antigravity on 10/07/26.
//

import UIKit

class ReportPDFGenerator {
    
    static func generateReportPDF(
        title: String,
        date: String,
        patientName: String,
        summary: String,
        detailedAnalysis: String,
        highlights: [ReportInsight],
        attachments: [Attachment]
    ) -> URL? {
        
        let pdfData = NSMutableData()
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
        
        UIGraphicsBeginPDFContextToData(pdfData, pageRect, nil)
        
        var currentPageNum = 1
        
        // Helper to start a new page
        func startNewPage() {
            UIGraphicsBeginPDFPage()
            drawHeaderAndFooter(pageNum: currentPageNum)
            currentPageNum += 1
        }
        
        func drawHeaderAndFooter(pageNum: Int) {
            // Draw a professional colored top header bar
            let primaryColor = UIColor(red: 67/255, green: 56/255, blue: 202/255, alpha: 1.0)
            let headerRect = CGRect(x: 0, y: 0, width: pageRect.width, height: 60)
            primaryColor.setFill()
            UIRectFill(headerRect)
            
            // App name / title in header
            let headerTitle = "CureMeGPT - Medical Report Analysis"
            let headerTitleAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.boldSystemFont(ofSize: 14),
                .foregroundColor: UIColor.white
            ]
            headerTitle.draw(at: CGPoint(x: 36, y: 22), withAttributes: headerTitleAttributes)
            
            // Draw Footer
            let footerText = "Page \(pageNum)"
            let footerAttributes: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10),
                .foregroundColor: UIColor.gray
            ]
            let footerSize = footerText.size(withAttributes: footerAttributes)
            footerText.draw(at: CGPoint(x: pageRect.width - footerSize.width - 36, y: pageRect.height - 36), withAttributes: footerAttributes)
            
            let footerDisclaimer = "Generated by CureMeGPT AI. Confidential medical record."
            footerDisclaimer.draw(at: CGPoint(x: 36, y: pageRect.height - 36), withAttributes: footerAttributes)
        }
        
        // Start first page
        startNewPage()
        
        var currentY: CGFloat = 80
        let margin: CGFloat = 36
        let contentWidth = pageRect.width - (margin * 2)
        
        // Typography styling
        let primaryColor = UIColor(red: 67/255, green: 56/255, blue: 202/255, alpha: 1.0)
        let secondaryColor = UIColor(red: 99/255, green: 107/255, blue: 118/255, alpha: 1.0)
        
        let titleAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 22),
            .foregroundColor: UIColor.black
        ]
        
        let dateAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: secondaryColor
        ]
        
        let sectionTitleAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 16),
            .foregroundColor: primaryColor
        ]
        
        let bodyAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor(red: 50/255, green: 50/255, blue: 50/255, alpha: 1.0)
        ]
        
        func checkSpaceAndStartNewPageIfNeeded(heightNeeded: CGFloat) {
            if currentY + heightNeeded > pageRect.height - 54 {
                startNewPage()
                currentY = 80
            }
        }
        
        // 1. Draw Report Title
        var rTitle = title.isEmpty ? "Medical Report Details" : title
        if rTitle.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() == "user uploaded a file" {
            rTitle = "Medical Report Details"
        }
        
        let rTitleHeight = rTitle.boundingRect(
            with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
            options: .usesLineFragmentOrigin,
            attributes: titleAttributes,
            context: nil
        ).height
        
        checkSpaceAndStartNewPageIfNeeded(heightNeeded: rTitleHeight)
        rTitle.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: rTitleHeight), withAttributes: titleAttributes)
        currentY += rTitleHeight + 8
        
        // 2. Draw Patient & Date info
        let patientStr = "Patient: \(patientName.isEmpty ? "Unknown" : patientName)"
        let dateStr = "Date: \(date.isEmpty ? "N/A" : date)"
        let infoStr = "\(patientStr)  |  \(dateStr)"
        let infoHeight = infoStr.boundingRect(
            with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
            options: .usesLineFragmentOrigin,
            attributes: dateAttributes,
            context: nil
        ).height
        
        checkSpaceAndStartNewPageIfNeeded(heightNeeded: infoHeight)
        infoStr.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: infoHeight), withAttributes: dateAttributes)
        currentY += infoHeight + 15
        
        // Divider line
        checkSpaceAndStartNewPageIfNeeded(heightNeeded: 5)
        let context = UIGraphicsGetCurrentContext()
        context?.setStrokeColor(secondaryColor.withAlphaComponent(0.3).cgColor)
        context?.setLineWidth(1)
        context?.move(to: CGPoint(x: margin, y: currentY))
        context?.addLine(to: CGPoint(x: pageRect.width - margin, y: currentY))
        context?.strokePath()
        currentY += 15
        
        // 3. Draw a Section Helper
        func drawSection(title: String, content: String) {
            guard !content.isEmpty else { return }
            
            // Section Title
            let sTitleHeight = title.boundingRect(
                with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                options: .usesLineFragmentOrigin,
                attributes: sectionTitleAttributes,
                context: nil
            ).height
            
            checkSpaceAndStartNewPageIfNeeded(heightNeeded: sTitleHeight + 10)
            title.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: sTitleHeight), withAttributes: sectionTitleAttributes)
            currentY += sTitleHeight + 8
            
            // Section Content (wrapped by paragraphs/lines)
            let paragraphs = content.components(separatedBy: "\n")
            for paragraph in paragraphs {
                let trimmed = paragraph.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !trimmed.isEmpty else { continue }
                
                let paragraphStyle = NSMutableParagraphStyle()
                paragraphStyle.lineSpacing = 4
                
                var attribs = bodyAttributes
                attribs[.paragraphStyle] = paragraphStyle
                
                let wordHeight = "A".size(withAttributes: attribs).height
                let lineHeight = wordHeight + 4
                
                let words = trimmed.components(separatedBy: " ")
                var currentLine = ""
                
                for word in words {
                    let testLine = currentLine.isEmpty ? word : "\(currentLine) \(word)"
                    let testSize = testLine.size(withAttributes: attribs)
                    if testSize.width > contentWidth && !currentLine.isEmpty {
                        // Current line needs to be drawn
                        checkSpaceAndStartNewPageIfNeeded(heightNeeded: lineHeight)
                        currentLine.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: lineHeight), withAttributes: attribs)
                        currentY += lineHeight
                        currentLine = word
                    } else {
                        currentLine = testLine
                    }
                }
                
                if !currentLine.isEmpty {
                    checkSpaceAndStartNewPageIfNeeded(heightNeeded: lineHeight)
                    currentLine.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: lineHeight), withAttributes: attribs)
                    currentY += lineHeight
                }
                
                currentY += 6 // paragraph spacing
            }
            
            currentY += 15 // section spacing
        }
        
        // Summary
        drawSection(title: "Summary", content: summary)
        
        // Detailed Analysis
        drawSection(title: "Detailed Analysis", content: detailedAnalysis)
        
        // AI Insights / Highlights
        if !highlights.isEmpty {
            let sTitleHeight = "AI Insights".boundingRect(
                with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                options: .usesLineFragmentOrigin,
                attributes: sectionTitleAttributes,
                context: nil
            ).height
            
            checkSpaceAndStartNewPageIfNeeded(heightNeeded: sTitleHeight + 10)
            "AI Insights".draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: sTitleHeight), withAttributes: sectionTitleAttributes)
            currentY += sTitleHeight + 8
            
            for item in highlights {
                let bulletStr = "• \(item.title): \(item.value)"
                let bulletHeight = bulletStr.boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: .usesLineFragmentOrigin,
                    attributes: bodyAttributes,
                    context: nil
                ).height
                
                checkSpaceAndStartNewPageIfNeeded(heightNeeded: bulletHeight + 4)
                bulletStr.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: bulletHeight), withAttributes: bodyAttributes)
                currentY += bulletHeight + 6
            }
            currentY += 15
        }
        
        // Attached Files
        if !attachments.isEmpty {
            let sTitleHeight = "Attached Files".boundingRect(
                with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                options: .usesLineFragmentOrigin,
                attributes: sectionTitleAttributes,
                context: nil
            ).height
            
            checkSpaceAndStartNewPageIfNeeded(heightNeeded: sTitleHeight + 10)
            "Attached Files".draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: sTitleHeight), withAttributes: sectionTitleAttributes)
            currentY += sTitleHeight + 8
            
            for item in attachments {
                let bulletStr = "• \(item.name)"
                let bulletHeight = bulletStr.boundingRect(
                    with: CGSize(width: contentWidth, height: .greatestFiniteMagnitude),
                    options: .usesLineFragmentOrigin,
                    attributes: bodyAttributes,
                    context: nil
                ).height
                
                checkSpaceAndStartNewPageIfNeeded(heightNeeded: bulletHeight + 4)
                bulletStr.draw(in: CGRect(x: margin, y: currentY, width: contentWidth, height: bulletHeight), withAttributes: bodyAttributes)
                currentY += bulletHeight + 6
            }
        }
        
        UIGraphicsEndPDFContext()
        
        // Save to temporary file
        let cleanTitle = rTitle.trimmingCharacters(in: .whitespacesAndNewlines)
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .joined(separator: "_")
        let fileName = "Report_\(cleanTitle.isEmpty ? "Analysis" : cleanTitle).pdf"
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
        
        do {
            try pdfData.write(to: tempURL)
            return tempURL
        } catch {
            print("❌ Failed to write PDF data: \(error.localizedDescription)")
            return nil
        }
    }
}
