# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'CureMeGPT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseMessaging'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'Firebase/Crashlytics'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Firebase/Storage'
  pod 'lottie-ios'
  pod 'SDWebImageSwiftUI'
  pod 'Firebase/Auth'
  pod 'IQKeyboardManagerSwift'
  pod 'AppsFlyerFramework'

  # Pods for CureMeGPT

end
